
CREATE TABLE IF NOT EXISTS public.configuration
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT configuration_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.configuration
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.configuration_tag
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at date,
    last_modified_at date,
    configuration_entity_id bigint,
    CONSTRAINT configuration_tag_pkey PRIMARY KEY (id),
    CONSTRAINT config_tag_fkey FOREIGN KEY (configuration_entity_id)
        REFERENCES public.configuration (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.configuration_tag
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.configuration_variable
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at date,
    description character varying(255) COLLATE pg_catalog."default",
    last_modified_at date,
    max_value integer NOT NULL,
    min_value integer NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    unit integer NOT NULL,
    configuration_entity_id bigint,
    CONSTRAINT configuration_variable_pkey PRIMARY KEY (id),
    CONSTRAINT config_variable_fkey FOREIGN KEY (configuration_entity_id)
        REFERENCES public.configuration (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.configuration_variable
    OWNER to postgres;