create table configuration  (
                               id long generated by default as identity,
                               description varchar(255),
                               name varchar(255),
                               primary key (id)
);
create table configuration_tag (
                                   id long generated by default as identity,
                                   created_at date,
                                   last_modified_at date,
                                   configuration_entity_id long,
                                   primary key (id)
);
create table configuration_variable (
                                        id long generated by default as identity,
                                        created_at date,
                                        description varchar(255),
                                        last_modified_at date,
                                        max_value int4 not null,
                                        min_value int4 not null,
                                        name varchar(255),
                                        unit int4 not null,
                                        configuration_entity_id long,
                                        primary key (id)
);

alter table if exists configuration_tag add constraint config_tag_fkey foreign key (configuration_entity_id) references configuration;
alter table if exists configuration_variable add constraint config_variable_fkey foreign key (configuration_entity_id) references configuration
